# Generated by Django 3.2 on 2022-12-25 22:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('a', 'Accepted'), ('dg', 'Delivering'), ('dd', 'Delivered'), ('c', 'Closed')], default='a', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('time_in_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('creator_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
            ],
        ),
    ]
