# Generated by Django 4.1.4 on 2023-01-02 02:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0002_discountitem_sold_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='discount_price_or_percent',
        ),
        migrations.RemoveField(
            model_name='discountitem',
            name='category',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='price_or_percent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=11, validators=[django.core.validators.MinValueValidator(2.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='who_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountitem',
            name='who_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('pe', 'Price'), ('pt', 'Protsent')], default='pe', max_length=2),
        ),
    ]
