# Generated by Django 4.1.4 on 2023-01-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_remove_discount_discount_price_or_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountitem',
            name='booked',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
