# Generated by Django 4.1.4 on 2023-01-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_discountitem_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountitem',
            name='booked',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
