# Generated by Django 4.2 on 2025-05-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('general', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='company.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('c', 'Client'), ('cd', 'CompanyDirector'), ('cm', 'CompanyManager'), ('cp', 'CompanyPoster'), ('a', 'admin')], db_index=True, default='c', max_length=2),
        ),
    ]
