# Generated by Django 4.1.4 on 2022-12-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_currency_code'),
        ('accounts', '0003_remove_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.currency'),
        ),
    ]
