# Generated by Django 4.1.4 on 2022-12-30 13:04

import accounts.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_currency_code'),
        ('accounts', '0004_customuser_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.ForeignKey(default=accounts.services.get_default_currency, on_delete=django.db.models.deletion.PROTECT, to='general.currency'),
        ),
    ]
