# Generated by Django 4.1.4 on 2023-01-08 22:57

import accounts.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.services.upload_avatar_path),
        ),
    ]
