# Generated by Django 4.2 on 2025-05-06 18:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoute', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('address', models.CharField(max_length=150)),
                ('info_email', models.EmailField(max_length=254)),
                ('career_email', models.EmailField(blank=True, max_length=254)),
                ('working_time_start', models.CharField(max_length=50)),
                ('working_time_end', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('phone2', models.CharField(max_length=18)),
                ('summary_for_message', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor.fields.RichTextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faqs_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to=settings.AUTH_USER_MODEL)),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_currencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='aboutus')),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='things', to='general.aboutus')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_thing_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pluss', to='general.aboutus')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_plus_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='general.aboutus')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_group', to=settings.AUTH_USER_MODEL)),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_group_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
