# Generated by Django 4.1.4 on 2022-12-30 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('symbol', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to=settings.AUTH_USER_MODEL)),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_currencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
