# Generated by Django 4.1.4 on 2022-12-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
