# Generated by Django 4.1.4 on 2023-01-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_faqs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='SubscribeUs',
        ),
    ]
