# Generated by Django 4.1.4 on 2023-01-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_rename_contactus_subscribeus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('address', models.CharField(max_length=150)),
                ('info_email', models.EmailField(max_length=254)),
                ('career_email', models.EmailField(blank=True, max_length=254)),
                ('working_time_start', models.CharField(max_length=50)),
                ('working_time_end', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('phone2', models.CharField(max_length=18)),
            ],
        ),
    ]
