# Generated by Django 4.1.4 on 2023-01-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_contact_summary_for_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
