# Generated by Django 4.1.4 on 2023-01-03 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0010_contact_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoute', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='aboutus')),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.aboutus')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_thing_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.aboutus')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_plus_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.aboutus')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userdataondelete')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_group', to=settings.AUTH_USER_MODEL)),
                ('who_updated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aboutus_group_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
