# Generated by Django 4.1.4 on 2023-01-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_aboutus_aboutusthing_aboutusplus_aboutusgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusgroup',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='general.aboutus'),
        ),
        migrations.AlterField(
            model_name='aboutusplus',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pluss', to='general.aboutus'),
        ),
        migrations.AlterField(
            model_name='aboutusthing',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='things', to='general.aboutus'),
        ),
    ]
