# Generated by Django 4.2 on 2025-05-06 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('desc', models.CharField(blank=True, max_length=200)),
                ('transaction_code', models.CharField(blank=True, max_length=150)),
                ('fact_deliveried', models.DateField(blank=True, null=True)),
                ('delivery', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('np', 'Not paid'), ('do', 'At the departure office'), ('ca', 'Courier accepted'), ('it', 'In transit'), ('dd', 'Delivered'), ('sr', 'Sender rejection'), ('rn', 'Return'), ('wc', 'Waiting for confirmation'), ('nc', 'Not confirmed')], default='np', max_length=3)),
                ('payment_type', models.CharField(blank=True, max_length=4)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('currency_course', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('total_price_in_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=14)),
                ('terms', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('price_in_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('currency_course', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('discount_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
