# Generated by Django 4.1.4 on 2022-12-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
