# Generated by Django 4.1.4 on 2023-01-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency_course',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
