# Generated by Django 4.1.4 on 2023-01-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_course',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
