# Generated by Django 4.1.4 on 2023-01-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_currency_course_order_total_price_in_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
