# Generated by Django 4.1.4 on 2023-01-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('np', 'Not paid'), ('do', 'At the departure office'), ('ca', 'Courier accepted'), ('it', 'In transit'), ('dd', 'Delivered'), ('sr', 'Sender rejection'), ('rn', 'Return'), ('wc', 'Waiting for confirmation'), ('nc', 'Not confirmed')], default='np', max_length=3),
        ),
    ]
