# Generated by Django 4.1.4 on 2023-01-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
