# Generated by Django 4.1.4 on 2023-01-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_discount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
